export enum Actions {
  SET_PARKING_AREA = 'SET_PARKING_AREA',
  UPDATE_PARKING_AREA = 'UPDATE_PARKING_AREA',
  UPDATE_PARKING_SIZE = 'UPDATE_PARKING_SIZE',
  PARK_CAR = 'PARK_CAR',
  UNPARK_CAR = 'UNPARK_CAR',
}